services:
  book_db:
    image: "postgres:latest"
    expose:
      - 5432
    env_file:
      - ./back/.env
    networks:
      - week-book_back
    volumes:
      - ./book_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - ./back/.env
    depends_on:
      - book_db
    networks:
      - week-book_back
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin/

  fast-api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - ./back/.env
    depends_on:
      - book_db
    networks:
      - week-book_back

  tg-bot:
    build:
      context: ./tg-bot
      dockerfile: Dockerfile
    env_file:
      - ./tg-bot/.env
    networks:
      - week-book_back

networks:
  week-book_back:
    driver: bridge

