services:
  book_db:
    image: "postgres:latest"
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - week-book_back
    volumes:
      - ./book_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - book_db
    networks:
      - week-book_back
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin/

  fact-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - book_db
    networks:
      - week-book_back

networks:
  week-book_back:
    driver: bridge
