services:
  book_db:
    image: "postgres:latest"
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - week-book_back
    volumes:
      - ./book_data:/var/lib/postgresql/data

  fast-api:
    image: "dekter13/api:1.0.0"
    expose:
      - 80
    env_file:
      - .env
    depends_on:
      - book_db
    networks:
      - week-book_back

  tg-bot:
    image: "dekter13/tg-bot:1.0.0"
    env_file:
      - .env
    networks:
      - week-book_back

networks:
  week-book_back:
    driver: bridge

